# Generated by Django 2.2.5 on 2019-09-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'fop',
                'verbose_name_plural': 'fops',
            },
        ),
        migrations.CreateModel(
            name='Uo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'uo',
                'verbose_name_plural': 'uos',
            },
        ),
        migrations.CreateModel(
            name='UoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=755)),
                ('short_name', models.CharField(max_length=755)),
                ('edrpou', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=755)),
                ('boss', models.CharField(max_length=255)),
                ('kved', models.CharField(max_length=455)),
                ('stan', models.CharField(max_length=455)),
                ('founding_document_num', models.CharField(max_length=255)),
                ('records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ufop.Uo')),
            ],
            options={
                'verbose_name': 'uo record',
                'verbose_name_plural': 'uo records',
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('share', models.TextField()),
                ('founders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='ufop.UoRecord')),
            ],
            options={
                'verbose_name': 'founder',
                'verbose_name_plural': 'founders',
            },
        ),
        migrations.CreateModel(
            name='FopRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=455)),
                ('address', models.CharField(max_length=455)),
                ('kved', models.CharField(max_length=455)),
                ('stan', models.CharField(max_length=455)),
                ('records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ufop.Fop')),
            ],
            options={
                'verbose_name': 'fop record',
                'verbose_name_plural': 'Fop records',
            },
        ),
    ]
