# Generated by Django 2.2.5 on 2019-09-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufop', '0002_auto_20190906_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='fio',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='uorecord',
            name='boss',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='uorecord',
            name='founding_document_num',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='uorecord',
            name='kved',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='uorecord',
            name='stan',
            field=models.CharField(max_length=755),
        ),
    ]
